# This an empty secrets.toml that
# allows the application to run in desktop mode.

[openai]
api_key = ""

[auth]
redirect_uri = ""
cookie_secret = "desktop-mode-placeholder-secret-12345678901234567890"
client_id = ""
client_secret = ""
server_metadata_url = ""

[firestore]
key_dict = { }
